# Site settings
title: JabCon
email: 
description: JabCon conference site
baseurl: "/JabCon"
url: "http://jabref.github.io/"
github_username: koppor

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]