# Site settings
title: JabCon
description: JabCon conference site
url: "https://jabcon.jabref.org/"
github_username: JabRef

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
